// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Annotation is a labeled point projected onto the image plane.
 */
export class Annotation {
    "x": number;
    "y": number;
    "label": string;

    /**
     * "star" or "dso"
     */
    "type": string;
    "mag": number;

    /** Creates a new Annotation instance. */
    constructor($$source: Partial<Annotation> = {}) {
        if (!("x" in $$source)) {
            this["x"] = 0;
        }
        if (!("y" in $$source)) {
            this["y"] = 0;
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("mag" in $$source)) {
            this["mag"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Annotation instance from a string or object.
     */
    static createFrom($$source: any = {}): Annotation {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Annotation($$parsedSource as Partial<Annotation>);
    }
}
