// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * SirilInfo describes the detected (or user-configured) Siril installation.
 */
export class SirilInfo {
    "executable": string;
    "version": string;
    "available": boolean;

    /** Creates a new SirilInfo instance. */
    constructor($$source: Partial<SirilInfo> = {}) {
        if (!("executable" in $$source)) {
            this["executable"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("available" in $$source)) {
            this["available"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SirilInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): SirilInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SirilInfo($$parsedSource as Partial<SirilInfo>);
    }
}
