// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * FrameMeta holds user-editable metadata fields that can be overridden in the DB
 * without touching the underlying FITS file.
 */
export class FrameMeta {
    "Object": string;
    "Telescope": string;
    "Filter": string;
    "DateObs": string;

    /** Creates a new FrameMeta instance. */
    constructor($$source: Partial<FrameMeta> = {}) {
        if (!("Object" in $$source)) {
            this["Object"] = "";
        }
        if (!("Telescope" in $$source)) {
            this["Telescope"] = "";
        }
        if (!("Filter" in $$source)) {
            this["Filter"] = "";
        }
        if (!("DateObs" in $$source)) {
            this["DateObs"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FrameMeta instance from a string or object.
     */
    static createFrom($$source: any = {}): FrameMeta {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FrameMeta($$parsedSource as Partial<FrameMeta>);
    }
}

/**
 * Prefs is the typed snapshot of all user preferences, serialised to/from the
 * database as plain strings.
 */
export class Prefs {
    "rootFolder": string;
    "basicCollapsed": boolean;
    "advancedCollapsed": boolean;
    "stretchEnabled": boolean;
    "stretchLevel": number;
    "columnConfig": string;
    "libraryColumnConfig": string;
    "sirilPath": string;
    "projectsFolder": string;
    "theme": string;

    /** Creates a new Prefs instance. */
    constructor($$source: Partial<Prefs> = {}) {
        if (!("rootFolder" in $$source)) {
            this["rootFolder"] = "";
        }
        if (!("basicCollapsed" in $$source)) {
            this["basicCollapsed"] = false;
        }
        if (!("advancedCollapsed" in $$source)) {
            this["advancedCollapsed"] = false;
        }
        if (!("stretchEnabled" in $$source)) {
            this["stretchEnabled"] = false;
        }
        if (!("stretchLevel" in $$source)) {
            this["stretchLevel"] = 0;
        }
        if (!("columnConfig" in $$source)) {
            this["columnConfig"] = "";
        }
        if (!("libraryColumnConfig" in $$source)) {
            this["libraryColumnConfig"] = "";
        }
        if (!("sirilPath" in $$source)) {
            this["sirilPath"] = "";
        }
        if (!("projectsFolder" in $$source)) {
            this["projectsFolder"] = "";
        }
        if (!("theme" in $$source)) {
            this["theme"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Prefs instance from a string or object.
     */
    static createFrom($$source: any = {}): Prefs {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Prefs($$parsedSource as Partial<Prefs>);
    }
}
