// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Candidate is a file in the source folder not yet in the library.
 */
export class Candidate {
    "sourcePath": string;

    /**
     * full path relative to source root (for tree display)
     */
    "relativePath": string;

    /**
     * flattened: nasRoot/immediateParentDir/filename
     */
    "destPath": string;
    "fileSize": number;

    /**
     * SHA-256 of first 1 MiB; set during import
     */
    "fileHash"?: string;

    /** Creates a new Candidate instance. */
    constructor($$source: Partial<Candidate> = {}) {
        if (!("sourcePath" in $$source)) {
            this["sourcePath"] = "";
        }
        if (!("relativePath" in $$source)) {
            this["relativePath"] = "";
        }
        if (!("destPath" in $$source)) {
            this["destPath"] = "";
        }
        if (!("fileSize" in $$source)) {
            this["fileSize"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Candidate instance from a string or object.
     */
    static createFrom($$source: any = {}): Candidate {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Candidate($$parsedSource as Partial<Candidate>);
    }
}
