// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {browser} from '../models';
import {fits} from '../models';

export function GeneratePreview(arg1:string,arg2:number):Promise<string>;

export function ListDirectory(arg1:string):Promise<Array<browser.FileEntry>>;

export function ReadFITSHeader(arg1:string):Promise<fits.FITSHeader>;

export function SelectRootFolder():Promise<string>;
