// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {prefs} from '../models';

export function AddFramesToProject(arg1:string,arg2:Array<string>,arg3:string):Promise<void>;

export function AnalyzeFrames(arg1:Array<string>):Promise<void>;

export function BatchHardDeleteFiles(arg1:Array<string>):Promise<void>;

export function BatchRejectFiles(arg1:Array<string>):Promise<void>;

export function BatchUnrejectFiles(arg1:Array<string>):Promise<void>;

export function BuildIndex(arg1:string):Promise<void>;

export function CancelAnalysis():Promise<void>;

export function CancelIndex():Promise<void>;

export function CheckSiril():Promise<app.SirilInfo>;

export function CreateProject(arg1:string,arg2:string):Promise<app.Project>;

export function DeleteProject(arg1:number):Promise<void>;

export function GeneratePreview(arg1:string,arg2:number):Promise<string>;

export function GeneratePreviewRaw(arg1:string):Promise<app.RawPreviewData>;

export function GetAppInfo():Promise<app.AppInfo>;

export function GetLibraryFrames(arg1:string):Promise<Array<app.LibraryFrame>>;

export function GetLightFramesPaged(arg1:string,arg2:Array<string>,arg3:number):Promise<app.PagedLightFrames>;

export function GetLightObjects(arg1:string):Promise<Array<string>>;

export function GetProjectFrames(arg1:string):Promise<Array<string>>;

export function GetProjectLibraryFrames(arg1:string):Promise<Array<app.LibraryFrame>>;

export function GetProjectOutputFiles(arg1:string):Promise<Array<app.ProjectOutputFile>>;

export function GetProjectsFolder():Promise<string>;

export function HardDeleteFile(arg1:string):Promise<void>;

export function ImportOutputFiles(arg1:Array<string>,arg2:string):Promise<void>;

export function ListDirectory(arg1:string):Promise<Array<app.FileEntry>>;

export function ListDirectoryEnriched(arg1:string):Promise<Array<app.EnrichedFileEntry>>;

export function ListProjects():Promise<Array<app.Project>>;

export function LoadPrefs():Promise<prefs.Prefs>;

export function OpenProjectInSiril(arg1:string):Promise<void>;

export function OpenWithSiril(arg1:string):Promise<void>;

export function ReadFITSHeader(arg1:string):Promise<app.FITSHeader>;

export function RejectFile(arg1:string):Promise<void>;

export function RemoveFramesFromProject(arg1:string,arg2:Array<string>):Promise<void>;

export function ScanImportCandidates(arg1:string,arg2:Array<string>):Promise<Array<app.ImportCandidate>>;

export function SelectProjectsFolder():Promise<string>;

export function SelectRootFolder():Promise<string>;

export function SelectSirilExecutable():Promise<string>;

export function SelectSourceFolder():Promise<string>;

export function SetFrameType(arg1:string,arg2:string):Promise<void>;

export function SetPref(arg1:string,arg2:string):Promise<void>;

export function SetProjectsFolder(arg1:string):Promise<void>;

export function SetSirilPath(arg1:string):Promise<void>;

export function StartImport(arg1:string,arg2:Array<string>,arg3:boolean):Promise<void>;

export function UnrejectFile(arg1:string):Promise<void>;
