// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GeneratePreview(arg1) {
  return window['go']['app']['App']['GeneratePreview'](arg1);
}

export function ListDirectory(arg1) {
  return window['go']['app']['App']['ListDirectory'](arg1);
}

export function ReadFITSHeader(arg1) {
  return window['go']['app']['App']['ReadFITSHeader'](arg1);
}

export function SelectRootFolder() {
  return window['go']['app']['App']['SelectRootFolder']();
}
