// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BuildIndex(arg1) {
  return window['go']['app']['App']['BuildIndex'](arg1);
}

export function CancelIndex() {
  return window['go']['app']['App']['CancelIndex']();
}

export function GeneratePreview(arg1, arg2) {
  return window['go']['app']['App']['GeneratePreview'](arg1, arg2);
}

export function ListDirectory(arg1) {
  return window['go']['app']['App']['ListDirectory'](arg1);
}

export function ListDirectoryEnriched(arg1) {
  return window['go']['app']['App']['ListDirectoryEnriched'](arg1);
}

export function LoadPrefs() {
  return window['go']['app']['App']['LoadPrefs']();
}

export function ReadFITSHeader(arg1) {
  return window['go']['app']['App']['ReadFITSHeader'](arg1);
}

export function SelectRootFolder() {
  return window['go']['app']['App']['SelectRootFolder']();
}

export function SetPref(arg1, arg2) {
  return window['go']['app']['App']['SetPref'](arg1, arg2);
}
