// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFramesToProject(arg1, arg2, arg3) {
  return window['go']['app']['App']['AddFramesToProject'](arg1, arg2, arg3);
}

export function AnalyzeFrames(arg1) {
  return window['go']['app']['App']['AnalyzeFrames'](arg1);
}

export function BuildIndex(arg1) {
  return window['go']['app']['App']['BuildIndex'](arg1);
}

export function CancelAnalysis() {
  return window['go']['app']['App']['CancelAnalysis']();
}

export function CancelIndex() {
  return window['go']['app']['App']['CancelIndex']();
}

export function CheckSiril() {
  return window['go']['app']['App']['CheckSiril']();
}

export function CreateProject(arg1, arg2) {
  return window['go']['app']['App']['CreateProject'](arg1, arg2);
}

export function DeleteProject(arg1) {
  return window['go']['app']['App']['DeleteProject'](arg1);
}

export function GeneratePreview(arg1, arg2) {
  return window['go']['app']['App']['GeneratePreview'](arg1, arg2);
}

export function GeneratePreviewRaw(arg1) {
  return window['go']['app']['App']['GeneratePreviewRaw'](arg1);
}

export function GetAppInfo() {
  return window['go']['app']['App']['GetAppInfo']();
}

export function GetLibraryFrames(arg1) {
  return window['go']['app']['App']['GetLibraryFrames'](arg1);
}

export function GetProjectFrames(arg1) {
  return window['go']['app']['App']['GetProjectFrames'](arg1);
}

export function GetProjectOutputFiles(arg1) {
  return window['go']['app']['App']['GetProjectOutputFiles'](arg1);
}

export function GetProjectsFolder() {
  return window['go']['app']['App']['GetProjectsFolder']();
}

export function HardDeleteFile(arg1) {
  return window['go']['app']['App']['HardDeleteFile'](arg1);
}

export function ImportOutputFiles(arg1, arg2) {
  return window['go']['app']['App']['ImportOutputFiles'](arg1, arg2);
}

export function ListDirectory(arg1) {
  return window['go']['app']['App']['ListDirectory'](arg1);
}

export function ListDirectoryEnriched(arg1) {
  return window['go']['app']['App']['ListDirectoryEnriched'](arg1);
}

export function ListProjects() {
  return window['go']['app']['App']['ListProjects']();
}

export function LoadPrefs() {
  return window['go']['app']['App']['LoadPrefs']();
}

export function OpenProjectInSiril(arg1) {
  return window['go']['app']['App']['OpenProjectInSiril'](arg1);
}

export function OpenWithSiril(arg1) {
  return window['go']['app']['App']['OpenWithSiril'](arg1);
}

export function ReadFITSHeader(arg1) {
  return window['go']['app']['App']['ReadFITSHeader'](arg1);
}

export function RejectFile(arg1) {
  return window['go']['app']['App']['RejectFile'](arg1);
}

export function ScanImportCandidates(arg1) {
  return window['go']['app']['App']['ScanImportCandidates'](arg1);
}

export function SelectProjectsFolder() {
  return window['go']['app']['App']['SelectProjectsFolder']();
}

export function SelectRootFolder() {
  return window['go']['app']['App']['SelectRootFolder']();
}

export function SelectSirilExecutable() {
  return window['go']['app']['App']['SelectSirilExecutable']();
}

export function SelectSourceFolder() {
  return window['go']['app']['App']['SelectSourceFolder']();
}

export function SetFrameType(arg1, arg2) {
  return window['go']['app']['App']['SetFrameType'](arg1, arg2);
}

export function SetPref(arg1, arg2) {
  return window['go']['app']['App']['SetPref'](arg1, arg2);
}

export function SetProjectsFolder(arg1) {
  return window['go']['app']['App']['SetProjectsFolder'](arg1);
}

export function SetSirilPath(arg1) {
  return window['go']['app']['App']['SetSirilPath'](arg1);
}

export function StartImport(arg1) {
  return window['go']['app']['App']['StartImport'](arg1);
}

export function UnrejectFile(arg1) {
  return window['go']['app']['App']['UnrejectFile'](arg1);
}
