// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ChannelStats holds per-channel statistics needed by the frontend to compute
 * MTF stretch uniforms without a second backend round-trip.
 */
export class ChannelStats {
    "median": number;
    "sigma": number;

    /** Creates a new ChannelStats instance. */
    constructor($$source: Partial<ChannelStats> = {}) {
        if (!("median" in $$source)) {
            this["median"] = 0;
        }
        if (!("sigma" in $$source)) {
            this["sigma"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChannelStats instance from a string or object.
     */
    static createFrom($$source: any = {}): ChannelStats {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ChannelStats($$parsedSource as Partial<ChannelStats>);
    }
}

/**
 * FITSHeader holds FITS metadata relevant to astrophotography.
 * Multiple keyword aliases are tried for each field (e.g. EXPTIME vs EXPOSURE)
 * to cover different camera conventions.
 */
export class FITSHeader {
    "width": number;
    "height": number;
    "channels": number;
    "bitpix": number;
    "object": string;
    "telescope": string;
    "instrument": string;
    "filter": string;
    "exptime": number;
    "dateObs": string;
    "gain": number;
    "offset": number;
    "ccdTemp": number;
    "ra": number;
    "dec": number;
    "xbinning": number;
    "ybinning": number;
    "focalLen": number;
    "siteElev": number;
    "siteLat": number;
    "siteLong": number;

    /**
     * WCS-derived pixel scale in arcsec/pixel and field rotation in degrees.
     * Non-zero only when the header contains usable WCS keywords.
     */
    "pixelScale": number;
    "rotation": number;
    "extra": { [_ in string]?: any };

    /** Creates a new FITSHeader instance. */
    constructor($$source: Partial<FITSHeader> = {}) {
        if (!("width" in $$source)) {
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            this["height"] = 0;
        }
        if (!("channels" in $$source)) {
            this["channels"] = 0;
        }
        if (!("bitpix" in $$source)) {
            this["bitpix"] = 0;
        }
        if (!("object" in $$source)) {
            this["object"] = "";
        }
        if (!("telescope" in $$source)) {
            this["telescope"] = "";
        }
        if (!("instrument" in $$source)) {
            this["instrument"] = "";
        }
        if (!("filter" in $$source)) {
            this["filter"] = "";
        }
        if (!("exptime" in $$source)) {
            this["exptime"] = 0;
        }
        if (!("dateObs" in $$source)) {
            this["dateObs"] = "";
        }
        if (!("gain" in $$source)) {
            this["gain"] = 0;
        }
        if (!("offset" in $$source)) {
            this["offset"] = 0;
        }
        if (!("ccdTemp" in $$source)) {
            this["ccdTemp"] = 0;
        }
        if (!("ra" in $$source)) {
            this["ra"] = 0;
        }
        if (!("dec" in $$source)) {
            this["dec"] = 0;
        }
        if (!("xbinning" in $$source)) {
            this["xbinning"] = 0;
        }
        if (!("ybinning" in $$source)) {
            this["ybinning"] = 0;
        }
        if (!("focalLen" in $$source)) {
            this["focalLen"] = 0;
        }
        if (!("siteElev" in $$source)) {
            this["siteElev"] = 0;
        }
        if (!("siteLat" in $$source)) {
            this["siteLat"] = 0;
        }
        if (!("siteLong" in $$source)) {
            this["siteLong"] = 0;
        }
        if (!("pixelScale" in $$source)) {
            this["pixelScale"] = 0;
        }
        if (!("rotation" in $$source)) {
            this["rotation"] = 0;
        }
        if (!("extra" in $$source)) {
            this["extra"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FITSHeader instance from a string or object.
     */
    static createFrom($$source: any = {}): FITSHeader {
        const $$createField23_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("extra" in $$parsedSource) {
            $$parsedSource["extra"] = $$createField23_0($$parsedSource["extra"]);
        }
        return new FITSHeader($$parsedSource as Partial<FITSHeader>);
    }
}

/**
 * RawPreviewData is returned by GeneratePreviewRawSized. The pixel data is a
 * base64-encoded little-endian float32 array in RGBA interleaved order
 * (R,G,B,1.0 per pixel, row-major, top-left origin). All channels are
 * globally normalised to [0,1] so colour balance is preserved; the
 * frontend applies MTF stretch using the Stats.
 */
export class RawPreviewData {
    "data": string;
    "width": number;
    "height": number;

    /**
     * 1 = mono, 3 = colour
     */
    "channels": number;
    "stats": ChannelStats[];

    /** Creates a new RawPreviewData instance. */
    constructor($$source: Partial<RawPreviewData> = {}) {
        if (!("data" in $$source)) {
            this["data"] = "";
        }
        if (!("width" in $$source)) {
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            this["height"] = 0;
        }
        if (!("channels" in $$source)) {
            this["channels"] = 0;
        }
        if (!("stats" in $$source)) {
            this["stats"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RawPreviewData instance from a string or object.
     */
    static createFrom($$source: any = {}): RawPreviewData {
        const $$createField4_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("stats" in $$parsedSource) {
            $$parsedSource["stats"] = $$createField4_0($$parsedSource["stats"]);
        }
        return new RawPreviewData($$parsedSource as Partial<RawPreviewData>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = ChannelStats.createFrom;
const $$createType2 = $Create.Array($$createType1);
