// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as catalog$0 from "../catalog/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as fits$0 from "../fits/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as importer$0 from "../importer/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as siril$0 from "../siril/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "../store/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddFramesToProject symlinks or copies NAS frames into the project, routing
 * each into lights/, darks/, flats/ or biases/ by its frame type. mode must be
 * "symlink" or "copy". Frames of other types are skipped (and logged); an
 * error is returned only if frames were requested but none could be placed.
 * See AddFramesToProjectDetailed for per-call counts.
 */
export function AddFramesToProject(projectFolder: string, nasPaths: string[], mode: string): $CancellablePromise<void> {
    return $Call.ByID(1804889247, projectFolder, nasPaths, mode);
}

/**
 * AddFramesToProjectDetailed is AddFramesToProject returning what happened.
 * An entry with the same name that refers to the same source is left alone;
 * one that refers to a different source gets a numeric suffix (name_2.fit).
 */
export function AddFramesToProjectDetailed(projectFolder: string, nasPaths: string[], mode: string): $CancellablePromise<$models.AddFramesResult> {
    return $Call.ByID(598750943, projectFolder, nasPaths, mode).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * AnalyzeFrames runs Siril headless analysis (findstar + platesolve + statistics) on each
 * NAS path sequentially. Raw output is written to $TMPDIR/eirin-siril-debug.txt.
 */
export function AnalyzeFrames(nasPaths: string[]): $CancellablePromise<void> {
    return $Call.ByID(1959591080, nasPaths);
}

/**
 * BackupDatabase writes a consistent copy of the SQLite database (including
 * changes still in the WAL) to the same directory with a timestamp suffix,
 * e.g. prefs_2026-06-05T153000.db. Returns the backup path.
 */
export function BackupDatabase(): $CancellablePromise<string> {
    return $Call.ByID(984395681);
}

/**
 * BatchHardDeleteFiles permanently removes multiple files from disk and their frame records.
 */
export function BatchHardDeleteFiles(paths: string[]): $CancellablePromise<void> {
    return $Call.ByID(2239500483, paths);
}

/**
 * BatchRejectFiles marks multiple files as rejected in a single transaction.
 */
export function BatchRejectFiles(paths: string[]): $CancellablePromise<void> {
    return $Call.ByID(1273238464, paths);
}

/**
 * BatchUnrejectFiles clears the rejection status on multiple files in a single transaction.
 */
export function BatchUnrejectFiles(paths: string[]): $CancellablePromise<void> {
    return $Call.ByID(2919265481, paths);
}

/**
 * BuildIndex traverses every subdirectory under rootPath, reads FITS headers
 * for files not yet in the cache, and stores them. Progress is reported via
 * "index:progress" Wails events. When force is true, already-indexed files are
 * re-read and overwritten (WCS plate-solve results are preserved).
 * 
 * Starting a new run supersedes (cancels) any run in progress; the superseded
 * run stops emitting events so it can't overwrite the new run's progress.
 * Every run ends with a "done" or "cancelled" event — if rootPath is empty or
 * not an accessible directory, a "done" event carrying Error is emitted.
 */
export function BuildIndex(rootPath: string, force: boolean): $CancellablePromise<void> {
    return $Call.ByID(2469627606, rootPath, force);
}

/**
 * CancelAnalysis interrupts an in-progress AnalyzeFrames call.
 */
export function CancelAnalysis(): $CancellablePromise<void> {
    return $Call.ByID(2126577498);
}

/**
 * CancelImport stops the running import after the file currently being
 * processed. The run then emits a final "import:progress" with phase
 * "cancelled". No-op if nothing is running.
 */
export function CancelImport(): $CancellablePromise<void> {
    return $Call.ByID(1282660021);
}

/**
 * CancelIndex stops any running BuildIndex operation.
 */
export function CancelIndex(): $CancellablePromise<void> {
    return $Call.ByID(3410097860);
}

/**
 * CheckSiril runs the configured siril executable with -v and returns version info.
 */
export function CheckSiril(): $CancellablePromise<$models.SirilInfo> {
    return $Call.ByID(1088539049).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * CreateProject creates a new project: DB record + folder with lights/,
 * darks/, flats/ and biases/ subfolders. It fails if the sanitized folder
 * already exists on disk (e.g. "M31 Ha" and "M31_Ha" map to the same folder).
 */
export function CreateProject(name: string, description: string): $CancellablePromise<$models.Project> {
    return $Call.ByID(1805623471, name, description).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * DeleteProject removes the project from the database (does not delete files).
 */
export function DeleteProject(id: number): $CancellablePromise<void> {
    return $Call.ByID(257249502, id);
}

/**
 * GeneratePreview returns a JPEG preview as a base64 data URL, scaled to
 * 1024 px and cached in memory (Blink loops over the same frames).
 * stretchLevel: 0=linear, 1=gentle, 2=normal, 3=strong
 */
export function GeneratePreview(path: string, stretchLevel: number): $CancellablePromise<string> {
    return $Call.ByID(3798999711, path, stretchLevel);
}

/**
 * GeneratePreviewRawSized returns raw float32 RGBA pixel data (base64-encoded) plus
 * per-channel statistics for CPU/GPU-based MTF rendering on the frontend.
 * maxSize=0 means native resolution (no downscaling).
 */
export function GeneratePreviewRawSized(path: string, maxSize: number): $CancellablePromise<fits$0.RawPreviewData> {
    return $Call.ByID(3470306118, path, maxSize).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetAnnotations returns catalog objects visible within the frame defined by the
 * plate-solve result (raCenter/decCenter in degrees, pixelScale in arcsec/pixel,
 * rotation in degrees CCW from North, image dimensions in pixels).
 */
export function GetAnnotations(raCenter: number, decCenter: number, pixelScale: number, rotation: number, width: number, height: number): $CancellablePromise<catalog$0.Annotation[]> {
    return $Call.ByID(3201120012, raCenter, decCenter, pixelScale, rotation, width, height).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * GetAppInfo returns static runtime information about the application.
 */
export function GetAppInfo(): $CancellablePromise<$models.AppInfo> {
    return $Call.ByID(35635725).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * GetAtlasFrameSize reads pixel dimensions for any supported file type.
 * For FITS files the header is parsed; for PNG/JPEG/TIFF just the image size
 * is read (much cheaper — no full pixel decode). Called lazily by the frontend.
 */
export function GetAtlasFrameSize(nasPath: string): $CancellablePromise<$models.AtlasFrameSize> {
    return $Call.ByID(2946490455, nasPath).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * GetAtlasIndex returns all stacked and processed frames under rootPath that
 * have WCS coordinates stored in the DB. No FITS files are read — this is a
 * fast DB-only query that returns immediately even for large libraries.
 * Light frames are never included in the Atlas.
 */
export function GetAtlasIndex(rootPath: string): $CancellablePromise<$models.AtlasIndexEntry[]> {
    return $Call.ByID(580963003, rootPath).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * GetCatalog returns all catalog objects (stars and DSOs) for the Sky Atlas star layer.
 */
export function GetCatalog(): $CancellablePromise<$models.CatalogObject[]> {
    return $Call.ByID(797145757).then(($result: any) => {
        return $$createType11($result);
    });
}

/**
 * GetFrameTypeSummary returns a breakdown of frame counts and total size by frame type under rootPath.
 */
export function GetFrameTypeSummary(rootPath: string): $CancellablePromise<$models.StorageNode[]> {
    return $Call.ByID(1792517689, rootPath).then(($result: any) => {
        return $$createType13($result);
    });
}

/**
 * GetImportStatus returns the latest import progress snapshot, or a progress
 * with Phase "idle" if no import has run since startup.
 */
export function GetImportStatus(): $CancellablePromise<$models.ImportProgress> {
    return $Call.ByID(726154637).then(($result: any) => {
        return $$createType14($result);
    });
}

/**
 * GetLibraryFrames returns all indexed frames under rootPath, converted to the
 * LibraryFrame shape for the frontend library view.
 */
export function GetLibraryFrames(rootPath: string): $CancellablePromise<$models.LibraryFrame[]> {
    return $Call.ByID(3745958251, rootPath).then(($result: any) => {
        return $$createType16($result);
    });
}

/**
 * GetLibraryFramesByType returns the indexed frames of one frame type (light,
 * dark, flat, bias, …) under rootPath — e.g. calibration frames for the
 * project frame picker, without loading the whole library.
 */
export function GetLibraryFramesByType(rootPath: string, frameType: string): $CancellablePromise<$models.LibraryFrame[]> {
    return $Call.ByID(2996506086, rootPath, frameType).then(($result: any) => {
        return $$createType16($result);
    });
}

/**
 * GetLightCoverage groups the non-rejected light frames under rootPath by
 * telescope and framing. Lights without WCS are placed (Approx) where other
 * frames of their OBJECT were measured or at its catalog position, or, failing
 * both, listed as unplaced.
 */
export function GetLightCoverage(rootPath: string): $CancellablePromise<$models.LightCoverage> {
    return $Call.ByID(3788933880, rootPath).then(($result: any) => {
        return $$createType17($result);
    });
}

/**
 * GetLightFramesPaged returns a page of light frames under rootPath filtered to
 * the given objects. offset=0 for the first page.
 */
export function GetLightFramesPaged(rootPath: string, objects: string[], offset: number): $CancellablePromise<$models.PagedLightFrames> {
    return $Call.ByID(2061787285, rootPath, objects, offset).then(($result: any) => {
        return $$createType18($result);
    });
}

/**
 * GetLightObjects returns the sorted list of distinct object names for light frames under rootPath.
 */
export function GetLightObjects(rootPath: string): $CancellablePromise<string[]> {
    return $Call.ByID(1824160294, rootPath).then(($result: any) => {
        return $$createType19($result);
    });
}

/**
 * GetProjectFrames lists the file names present in the project's frame
 * subfolders (lights/, darks/, flats/, biases/).
 */
export function GetProjectFrames(projectFolder: string): $CancellablePromise<string[]> {
    return $Call.ByID(3301776845, projectFolder).then(($result: any) => {
        return $$createType19($result);
    });
}

/**
 * GetProjectLibraryFrames returns full LibraryFrame metadata for every frame
 * in the project's frame subfolders, resolving symlinks back to the NAS source
 * path for the DB lookup. FrameType comes from the DB; frames not in the DB
 * are returned with their filename and the type implied by their subfolder.
 * Legacy projects with darks/biases inside lights/ are listed too.
 */
export function GetProjectLibraryFrames(projectFolder: string): $CancellablePromise<$models.LibraryFrame[]> {
    return $Call.ByID(2780196728, projectFolder).then(($result: any) => {
        return $$createType16($result);
    });
}

/**
 * GetProjectOutputFiles lists files directly in the project root folder,
 * skipping all subdirectories (including lights/, darks/, flats/, biases/ and
 * Siril's process/). These are the processed outputs created by Siril.
 */
export function GetProjectOutputFiles(projectFolder: string): $CancellablePromise<$models.ProjectOutputFile[]> {
    return $Call.ByID(2934423885, projectFolder).then(($result: any) => {
        return $$createType21($result);
    });
}

/**
 * GetProjectsFolder returns the configured projects root folder.
 */
export function GetProjectsFolder(): $CancellablePromise<string> {
    return $Call.ByID(4118089352);
}

/**
 * GetSnapshotStatus reports whether the library snapshot is being published,
 * where, and how the last attempt went.
 */
export function GetSnapshotStatus(): $CancellablePromise<$models.SnapshotStatus> {
    return $Call.ByID(2047036404).then(($result: any) => {
        return $$createType22($result);
    });
}

/**
 * GetStorageStats returns a two-level tree of disk usage:
 * root → objects → dates (YYYY-MM-DD), each leaf summing file_size and frame count.
 */
export function GetStorageStats(rootPath: string): $CancellablePromise<$models.StorageNode> {
    return $Call.ByID(3681786110, rootPath).then(($result: any) => {
        return $$createType12($result);
    });
}

/**
 * GetViewerPreview renders a preview on the server for the read-only viewer,
 * which reaches the backend over the network: a JPEG of at most
 * viewerPreviewSize pixels (~1 MB) instead of the raw float pixels or the
 * original file (tens of MB). FITS files are stretched at stretchLevel
 * (0=linear … 3=strong); raster images are shown as they are.
 */
export function GetViewerPreview(path: string, stretchLevel: number): $CancellablePromise<fits$0.RenderedPreview> {
    return $Call.ByID(2068264024, path, stretchLevel).then(($result: any) => {
        return $$createType23($result);
    });
}

/**
 * HardDeleteFile permanently removes a file from disk and cleans up its frame record.
 */
export function HardDeleteFile(path: string): $CancellablePromise<void> {
    return $Call.ByID(3019656550, path);
}

/**
 * ImportOutputFiles copies project output files to destFolder on the NAS,
 * then indexes each copied file so it appears in the library immediately.
 * 
 * It is all-or-nothing with respect to name conflicts: existing NAS files are
 * never overwritten, so if any destination already exists (or two sources
 * share a name), nothing is copied and the result lists the conflicting names
 * with a nil error. The error is reserved for real failures (invalid
 * destination, I/O errors); a copy failing midway keeps the files copied so
 * far (listed in Copied). Metadata (object, telescope, instrument, filter) is
 * inherited from the first project light frame found in the DB.
 */
export function ImportOutputFiles(filePaths: string[], destFolder: string): $CancellablePromise<$models.ImportOutputsResult> {
    return $Call.ByID(1641822381, filePaths, destFolder).then(($result: any) => {
        return $$createType24($result);
    });
}

export function ListDirectory(path: string): $CancellablePromise<$models.FileEntry[]> {
    return $Call.ByID(3367487933, path).then(($result: any) => {
        return $$createType26($result);
    });
}

/**
 * ListDirectoryEnriched returns directory entries enriched with cached FITS
 * header metadata. It is cache-only and returns immediately — files not yet in
 * the cache will have HasMeta=false. Run BuildIndex to populate the cache.
 */
export function ListDirectoryEnriched(path: string): $CancellablePromise<$models.EnrichedFileEntry[]> {
    return $Call.ByID(483950001, path).then(($result: any) => {
        return $$createType28($result);
    });
}

/**
 * ListProjects returns all projects from the database.
 */
export function ListProjects(): $CancellablePromise<$models.Project[]> {
    return $Call.ByID(2159218332).then(($result: any) => {
        return $$createType29($result);
    });
}

/**
 * LoadPrefs returns all persisted preferences, with defaults for missing keys.
 */
export function LoadPrefs(): $CancellablePromise<store$0.Prefs> {
    return $Call.ByID(2572957756).then(($result: any) => {
        return $$createType30($result);
    });
}

/**
 * LoadRasterImage returns a PNG, JPEG or TIFF file as a data URL a browser
 * can display (TIFF is converted to PNG). The file must be under the
 * configured NAS root.
 */
export function LoadRasterImage(path: string): $CancellablePromise<string> {
    return $Call.ByID(1706285520, path);
}

/**
 * OpenFolder opens path (or, for a file, its parent folder) in the OS file manager.
 */
export function OpenFolder(path: string): $CancellablePromise<void> {
    return $Call.ByID(968682538, path);
}

/**
 * OpenProjectInSiril launches Siril with the project folder as working directory.
 */
export function OpenProjectInSiril(projectFolder: string): $CancellablePromise<void> {
    return $Call.ByID(1221009315, projectFolder);
}

/**
 * OpenWithSiril launches the Siril GUI with the given file's parent directory
 * as the working directory (-d flag). Siril requires -d to set its working dir.
 */
export function OpenWithSiril(filePath: string): $CancellablePromise<void> {
    return $Call.ByID(2685951341, filePath);
}

/**
 * PublishSnapshot publishes the library snapshot now, whether or not anything
 * changed.
 */
export function PublishSnapshot(): $CancellablePromise<void> {
    return $Call.ByID(2432816017);
}

export function ReadFITSHeader(path: string): $CancellablePromise<fits$0.FITSHeader | null> {
    return $Call.ByID(3225654599, path).then(($result: any) => {
        return $$createType32($result);
    });
}

/**
 * RejectFile marks a file as soft-deleted. It remains on disk but is hidden
 * from the normal file listing until explicitly shown in the Rejected view.
 */
export function RejectFile(path: string): $CancellablePromise<void> {
    return $Call.ByID(1431182279, path);
}

/**
 * RemoveFramesFromProject removes the project entries (symlinks or copies) in
 * any frame subfolder that refer to the given NAS paths. NAS files are never
 * touched.
 */
export function RemoveFramesFromProject(projectFolder: string, nasPaths: string[]): $CancellablePromise<void> {
    return $Call.ByID(1305981425, projectFolder, nasPaths);
}

/**
 * RenameFrame renames a file on disk and updates the DB key accordingly.
 * The new name must be in the same directory as the old path.
 */
export function RenameFrame(oldPath: string, newName: string): $CancellablePromise<string> {
    return $Call.ByID(3392480449, oldPath, newName);
}

/**
 * RevealPath opens the OS file manager with path selected.
 */
export function RevealPath(path: string): $CancellablePromise<void> {
    return $Call.ByID(577569720, path);
}

/**
 * ScanImportCandidates walks sourceFolder and returns files whose basename does
 * not already appear in the frames database. extensions limits which file types
 * are included (e.g. ["fit","fits","png"]); an empty slice includes everything.
 * The destination path is flattened: nasRoot/immediateParentDir/filename.
 * Note: this scan is basename-only for speed. The actual hash-based duplicate
 * check happens during StartImport when files are read anyway.
 */
export function ScanImportCandidates(sourceFolder: string, extensions: string[]): $CancellablePromise<$models.ImportCandidate[]> {
    return $Call.ByID(3873197428, sourceFolder, extensions).then(($result: any) => {
        return $$createType34($result);
    });
}

/**
 * SelectProjectsFolder opens a directory picker for the projects root.
 */
export function SelectProjectsFolder(): $CancellablePromise<string> {
    return $Call.ByID(595001140);
}

export function SelectRootFolder(): $CancellablePromise<string> {
    return $Call.ByID(1530227910);
}

/**
 * SelectSirilExecutable opens a file-picker so the user can locate the siril binary.
 */
export function SelectSirilExecutable(): $CancellablePromise<string> {
    return $Call.ByID(3813294425);
}

/**
 * SelectSourceFolder opens an OS directory dialog for the user to pick the
 * folder they want to import files from.
 */
export function SelectSourceFolder(): $CancellablePromise<string> {
    return $Call.ByID(2446200491);
}

/**
 * SetFrameType lets the user manually override the classified type for a frame
 * (e.g. to promote a stacked image to "processed").
 */
export function SetFrameType(nasPath: string, frameType: string): $CancellablePromise<void> {
    return $Call.ByID(3309073619, nasPath, frameType);
}

/**
 * SetPref persists a single preference by key. Both key and value are strings;
 * booleans are "true"/"false" and integers are their decimal string form.
 */
export function SetPref(key: string, value: string): $CancellablePromise<void> {
    return $Call.ByID(3845670703, key, value);
}

/**
 * SetProjectsFolder persists the projects root folder preference.
 */
export function SetProjectsFolder(path: string): $CancellablePromise<void> {
    return $Call.ByID(1813591148, path);
}

/**
 * SetSirilPath persists a custom siril executable path. Pass an empty string to
 * revert to the default PATH lookup.
 */
export function SetSirilPath(path: string): $CancellablePromise<void> {
    return $Call.ByID(3296556194, path);
}

/**
 * StartImport re-scans sourceFolder, then copies qualifying files to the NAS
 * root in a background goroutine. extensions filters by file type (empty = all).
 * When deleteAfterCopy is true, a source file is removed only once an
 * identical copy (same size and full-file SHA-256) is confirmed in the library.
 * FITS files are indexed into the database immediately after being copied.
 * Progress is reported via "import:progress" events and GetImportStatus.
 * Returns an error if an import is already running, the NAS root is not
 * accessible, or the scan fails; per-file failures are reported in the final
 * progress event's Errors instead.
 */
export function StartImport(sourceFolder: string, extensions: string[], deleteAfterCopy: boolean): $CancellablePromise<void> {
    return $Call.ByID(1581009823, sourceFolder, extensions, deleteAfterCopy);
}

/**
 * SuggestRejects returns quality-analyzed light frames whose FWHM is more than
 * threshold standard deviations above the median for their (object, filter) group.
 * threshold defaults to 2.0 if ≤ 0.
 */
export function SuggestRejects(rootPath: string, threshold: number): $CancellablePromise<$models.SuggestResult[]> {
    return $Call.ByID(1563214480, rootPath, threshold).then(($result: any) => {
        return $$createType36($result);
    });
}

/**
 * UnrejectFile removes the soft-delete mark, making the file visible again.
 */
export function UnrejectFile(path: string): $CancellablePromise<void> {
    return $Call.ByID(2416326180, path);
}

/**
 * UpdateFrameMeta writes user-supplied metadata overrides into the DB.
 * Empty fields are ignored — they leave the existing value unchanged.
 */
export function UpdateFrameMeta(path: string, meta: store$0.FrameMeta): $CancellablePromise<void> {
    return $Call.ByID(530878317, path, meta);
}

// Private type creation functions
const $$createType0 = $models.AddFramesResult.createFrom;
const $$createType1 = siril$0.SirilInfo.createFrom;
const $$createType2 = $models.Project.createFrom;
const $$createType3 = fits$0.RawPreviewData.createFrom;
const $$createType4 = catalog$0.Annotation.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $models.AppInfo.createFrom;
const $$createType7 = $models.AtlasFrameSize.createFrom;
const $$createType8 = $models.AtlasIndexEntry.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = $models.CatalogObject.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = $models.StorageNode.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = importer$0.Progress.createFrom;
const $$createType15 = $models.LibraryFrame.createFrom;
const $$createType16 = $Create.Array($$createType15);
const $$createType17 = $models.LightCoverage.createFrom;
const $$createType18 = $models.PagedLightFrames.createFrom;
const $$createType19 = $Create.Array($Create.Any);
const $$createType20 = $models.ProjectOutputFile.createFrom;
const $$createType21 = $Create.Array($$createType20);
const $$createType22 = $models.SnapshotStatus.createFrom;
const $$createType23 = fits$0.RenderedPreview.createFrom;
const $$createType24 = $models.ImportOutputsResult.createFrom;
const $$createType25 = $models.FileEntry.createFrom;
const $$createType26 = $Create.Array($$createType25);
const $$createType27 = $models.EnrichedFileEntry.createFrom;
const $$createType28 = $Create.Array($$createType27);
const $$createType29 = $Create.Array($$createType2);
const $$createType30 = store$0.Prefs.createFrom;
const $$createType31 = fits$0.FITSHeader.createFrom;
const $$createType32 = $Create.Nullable($$createType31);
const $$createType33 = importer$0.Candidate.createFrom;
const $$createType34 = $Create.Array($$createType33);
const $$createType35 = $models.SuggestResult.createFrom;
const $$createType36 = $Create.Array($$createType35);
