// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as catalog$0 from "../catalog/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as fits$0 from "../fits/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as importer$0 from "../importer/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as siril$0 from "../siril/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "../store/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddFramesToProject symlinks or copies NAS frames into <projectFolder>/lights/.
 * mode must be "symlink" or "copy".
 */
export function AddFramesToProject(projectFolder: string, nasPaths: string[], mode: string): $CancellablePromise<void> {
    return $Call.ByID(1804889247, projectFolder, nasPaths, mode);
}

/**
 * AnalyzeFrames runs Siril headless analysis (findstar + platesolve + statistics) on each
 * NAS path sequentially. Raw output is written to $TMPDIR/eirin-siril-debug.txt.
 */
export function AnalyzeFrames(nasPaths: string[]): $CancellablePromise<void> {
    return $Call.ByID(1959591080, nasPaths);
}

/**
 * BackupDatabase copies the SQLite database to the same directory with a
 * timestamp suffix, e.g. prefs_2026-06-05T153000.db. Returns the backup path.
 */
export function BackupDatabase(): $CancellablePromise<string> {
    return $Call.ByID(984395681);
}

/**
 * BatchHardDeleteFiles permanently removes multiple files from disk and their frame records.
 */
export function BatchHardDeleteFiles(paths: string[]): $CancellablePromise<void> {
    return $Call.ByID(2239500483, paths);
}

/**
 * BatchRejectFiles marks multiple files as rejected in a single transaction.
 */
export function BatchRejectFiles(paths: string[]): $CancellablePromise<void> {
    return $Call.ByID(1273238464, paths);
}

/**
 * BatchUnrejectFiles clears the rejection status on multiple files in a single transaction.
 */
export function BatchUnrejectFiles(paths: string[]): $CancellablePromise<void> {
    return $Call.ByID(2919265481, paths);
}

/**
 * BuildIndex traverses every subdirectory under rootPath, reads FITS headers
 * for files not yet in the cache, and stores them. Progress is reported via
 * "index:progress" Wails events. When force is true, already-indexed files are
 * re-read and overwritten (WCS plate-solve results are preserved).
 */
export function BuildIndex(rootPath: string, force: boolean): $CancellablePromise<void> {
    return $Call.ByID(2469627606, rootPath, force);
}

/**
 * CancelAnalysis interrupts an in-progress AnalyzeFrames call.
 */
export function CancelAnalysis(): $CancellablePromise<void> {
    return $Call.ByID(2126577498);
}

/**
 * CancelIndex stops any running BuildIndex operation.
 */
export function CancelIndex(): $CancellablePromise<void> {
    return $Call.ByID(3410097860);
}

/**
 * CheckSiril runs the configured siril executable with -v and returns version info.
 */
export function CheckSiril(): $CancellablePromise<$models.SirilInfo> {
    return $Call.ByID(1088539049).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * CreateProject creates a new project: DB record + folder + lights subfolder.
 */
export function CreateProject(name: string, description: string): $CancellablePromise<$models.Project> {
    return $Call.ByID(1805623471, name, description).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * DeleteProject removes the project from the database (does not delete files).
 */
export function DeleteProject(id: number): $CancellablePromise<void> {
    return $Call.ByID(257249502, id);
}

/**
 * GeneratePreview returns a PNG preview as a base64 data URL, scaled to 1024 px.
 * stretchLevel: 0=linear, 1=gentle, 2=normal, 3=strong
 */
export function GeneratePreview(path: string, stretchLevel: number): $CancellablePromise<string> {
    return $Call.ByID(3798999711, path, stretchLevel);
}

/**
 * GeneratePreviewRawSized returns raw float32 RGBA pixel data (base64-encoded) plus
 * per-channel statistics for CPU/GPU-based MTF rendering on the frontend.
 * maxSize=0 means native resolution (no downscaling).
 */
export function GeneratePreviewRawSized(path: string, maxSize: number): $CancellablePromise<fits$0.RawPreviewData> {
    return $Call.ByID(3470306118, path, maxSize).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetAnnotations returns catalog objects visible within the frame defined by the
 * plate-solve result (raCenter/decCenter in degrees, pixelScale in arcsec/pixel,
 * rotation in degrees CCW from North, image dimensions in pixels).
 */
export function GetAnnotations(raCenter: number, decCenter: number, pixelScale: number, rotation: number, width: number, height: number): $CancellablePromise<catalog$0.Annotation[]> {
    return $Call.ByID(3201120012, raCenter, decCenter, pixelScale, rotation, width, height).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * GetAppInfo returns static runtime information about the application.
 */
export function GetAppInfo(): $CancellablePromise<$models.AppInfo> {
    return $Call.ByID(35635725).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * GetAtlasFrameSize reads pixel dimensions for any supported file type.
 * For FITS files the header is parsed; for PNG/TIFF the image config is decoded
 * (much cheaper — no full pixel decode). Called lazily by the frontend.
 */
export function GetAtlasFrameSize(nasPath: string): $CancellablePromise<$models.AtlasFrameSize> {
    return $Call.ByID(2946490455, nasPath).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * GetAtlasIndex returns all stacked and processed frames under rootPath that
 * have WCS coordinates stored in the DB. No FITS files are read — this is a
 * fast DB-only query that returns immediately even for large libraries.
 * Light frames are never included in the Atlas.
 */
export function GetAtlasIndex(rootPath: string): $CancellablePromise<$models.AtlasIndexEntry[]> {
    return $Call.ByID(580963003, rootPath).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * GetCatalog returns all catalog objects (stars and DSOs) for the Sky Atlas star layer.
 */
export function GetCatalog(): $CancellablePromise<$models.CatalogObject[]> {
    return $Call.ByID(797145757).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * GetFrameTypeSummary returns a breakdown of frame counts and total size by frame type under rootPath.
 */
export function GetFrameTypeSummary(rootPath: string): $CancellablePromise<$models.StorageNode[]> {
    return $Call.ByID(1792517689, rootPath).then(($result: any) => {
        return $$createType12($result);
    });
}

/**
 * GetLibraryFrames returns all indexed frames under rootPath, converted to the
 * LibraryFrame shape for the frontend library view.
 */
export function GetLibraryFrames(rootPath: string): $CancellablePromise<$models.LibraryFrame[]> {
    return $Call.ByID(3745958251, rootPath).then(($result: any) => {
        return $$createType14($result);
    });
}

/**
 * GetLightFramesPaged returns a page of light frames under rootPath filtered to
 * the given objects. offset=0 for the first page.
 */
export function GetLightFramesPaged(rootPath: string, objects: string[], offset: number): $CancellablePromise<$models.PagedLightFrames> {
    return $Call.ByID(2061787285, rootPath, objects, offset).then(($result: any) => {
        return $$createType15($result);
    });
}

/**
 * GetLightObjects returns the sorted list of distinct object names for light frames under rootPath.
 */
export function GetLightObjects(rootPath: string): $CancellablePromise<string[]> {
    return $Call.ByID(1824160294, rootPath).then(($result: any) => {
        return $$createType16($result);
    });
}

/**
 * GetProjectFrames lists filenames present in <projectFolder>/lights/.
 */
export function GetProjectFrames(projectFolder: string): $CancellablePromise<string[]> {
    return $Call.ByID(3301776845, projectFolder).then(($result: any) => {
        return $$createType16($result);
    });
}

/**
 * GetProjectLibraryFrames returns full LibraryFrame metadata for every frame in
 * <projectFolder>/lights/, resolving symlinks back to the NAS source path for
 * the DB lookup. Frames not yet in the DB are returned with just their filename.
 */
export function GetProjectLibraryFrames(projectFolder: string): $CancellablePromise<$models.LibraryFrame[]> {
    return $Call.ByID(2780196728, projectFolder).then(($result: any) => {
        return $$createType14($result);
    });
}

/**
 * GetProjectOutputFiles lists files directly in the project root folder,
 * skipping all subdirectories (including lights/). These are the processed
 * outputs created by Siril.
 */
export function GetProjectOutputFiles(projectFolder: string): $CancellablePromise<$models.ProjectOutputFile[]> {
    return $Call.ByID(2934423885, projectFolder).then(($result: any) => {
        return $$createType18($result);
    });
}

/**
 * GetProjectsFolder returns the configured projects root folder.
 */
export function GetProjectsFolder(): $CancellablePromise<string> {
    return $Call.ByID(4118089352);
}

/**
 * GetStorageStats returns a two-level tree of disk usage:
 * root → objects → dates (YYYY-MM-DD), each leaf summing file_size and frame count.
 */
export function GetStorageStats(rootPath: string): $CancellablePromise<$models.StorageNode> {
    return $Call.ByID(3681786110, rootPath).then(($result: any) => {
        return $$createType11($result);
    });
}

/**
 * HardDeleteFile permanently removes a file from disk and cleans up its frame record.
 */
export function HardDeleteFile(path: string): $CancellablePromise<void> {
    return $Call.ByID(3019656550, path);
}

/**
 * ImportOutputFiles copies project output files to destFolder on the NAS,
 * then indexes each copied file so it appears in the library immediately.
 * Metadata (object, telescope, instrument) is inherited from the first light
 * symlink found in the project's lights/ folder.
 */
export function ImportOutputFiles(filePaths: string[], destFolder: string): $CancellablePromise<void> {
    return $Call.ByID(1641822381, filePaths, destFolder);
}

export function ListDirectory(path: string): $CancellablePromise<$models.FileEntry[]> {
    return $Call.ByID(3367487933, path).then(($result: any) => {
        return $$createType20($result);
    });
}

/**
 * ListDirectoryEnriched returns directory entries enriched with cached FITS
 * header metadata. It is cache-only and returns immediately — files not yet in
 * the cache will have HasMeta=false. Run BuildIndex to populate the cache.
 */
export function ListDirectoryEnriched(path: string): $CancellablePromise<$models.EnrichedFileEntry[]> {
    return $Call.ByID(483950001, path).then(($result: any) => {
        return $$createType22($result);
    });
}

/**
 * ListProjects returns all projects from the database.
 */
export function ListProjects(): $CancellablePromise<$models.Project[]> {
    return $Call.ByID(2159218332).then(($result: any) => {
        return $$createType23($result);
    });
}

/**
 * LoadPrefs returns all persisted preferences, with defaults for missing keys.
 */
export function LoadPrefs(): $CancellablePromise<store$0.Prefs> {
    return $Call.ByID(2572957756).then(($result: any) => {
        return $$createType24($result);
    });
}

/**
 * LoadRasterImage reads a PNG file from disk and returns it as a base64-encoded
 * PNG data URL. The file must be under the configured NAS root.
 */
export function LoadRasterImage(path: string): $CancellablePromise<string> {
    return $Call.ByID(1706285520, path);
}

/**
 * OpenProjectInSiril launches Siril with the project folder as working directory.
 */
export function OpenProjectInSiril(projectFolder: string): $CancellablePromise<void> {
    return $Call.ByID(1221009315, projectFolder);
}

/**
 * OpenWithSiril launches the Siril GUI with the given file's parent directory
 * as the working directory (-d flag). Siril requires -d to set its working dir.
 */
export function OpenWithSiril(filePath: string): $CancellablePromise<void> {
    return $Call.ByID(2685951341, filePath);
}

export function ReadFITSHeader(path: string): $CancellablePromise<fits$0.FITSHeader | null> {
    return $Call.ByID(3225654599, path).then(($result: any) => {
        return $$createType26($result);
    });
}

/**
 * RejectFile marks a file as soft-deleted. It remains on disk but is hidden
 * from the normal file listing until explicitly shown in the Rejected view.
 */
export function RejectFile(path: string): $CancellablePromise<void> {
    return $Call.ByID(1431182279, path);
}

/**
 * RemoveFramesFromProject removes the file or symlink in <projectFolder>/lights/
 * whose basename matches each given NAS path.
 */
export function RemoveFramesFromProject(projectFolder: string, nasPaths: string[]): $CancellablePromise<void> {
    return $Call.ByID(1305981425, projectFolder, nasPaths);
}

/**
 * RenameFrame renames a file on disk and updates the DB key accordingly.
 * The new name must be in the same directory as the old path.
 */
export function RenameFrame(oldPath: string, newName: string): $CancellablePromise<string> {
    return $Call.ByID(3392480449, oldPath, newName);
}

/**
 * ScanImportCandidates walks sourceFolder and returns files whose basename does
 * not already appear in the frames database. extensions limits which file types
 * are included (e.g. ["fit","fits","png"]); an empty slice includes everything.
 * The destination path is flattened: nasRoot/immediateParentDir/filename.
 * Note: this scan is basename-only for speed. The actual hash-based duplicate
 * check happens during StartImport when files are read anyway.
 */
export function ScanImportCandidates(sourceFolder: string, extensions: string[]): $CancellablePromise<$models.ImportCandidate[]> {
    return $Call.ByID(3873197428, sourceFolder, extensions).then(($result: any) => {
        return $$createType28($result);
    });
}

/**
 * SelectProjectsFolder opens a directory picker for the projects root.
 */
export function SelectProjectsFolder(): $CancellablePromise<string> {
    return $Call.ByID(595001140);
}

export function SelectRootFolder(): $CancellablePromise<string> {
    return $Call.ByID(1530227910);
}

/**
 * SelectSirilExecutable opens a file-picker so the user can locate the siril binary.
 */
export function SelectSirilExecutable(): $CancellablePromise<string> {
    return $Call.ByID(3813294425);
}

/**
 * SelectSourceFolder opens an OS directory dialog for the user to pick the
 * folder they want to import files from.
 */
export function SelectSourceFolder(): $CancellablePromise<string> {
    return $Call.ByID(2446200491);
}

/**
 * SetFrameType lets the user manually override the classified type for a frame
 * (e.g. to promote a stacked image to "processed").
 */
export function SetFrameType(nasPath: string, frameType: string): $CancellablePromise<void> {
    return $Call.ByID(3309073619, nasPath, frameType);
}

/**
 * SetPref persists a single preference by key. Both key and value are strings;
 * booleans are "true"/"false" and integers are their decimal string form.
 */
export function SetPref(key: string, value: string): $CancellablePromise<void> {
    return $Call.ByID(3845670703, key, value);
}

/**
 * SetProjectsFolder persists the projects root folder preference.
 */
export function SetProjectsFolder(path: string): $CancellablePromise<void> {
    return $Call.ByID(1813591148, path);
}

/**
 * SetSirilPath persists a custom siril executable path. Pass an empty string to
 * revert to the default PATH lookup.
 */
export function SetSirilPath(path: string): $CancellablePromise<void> {
    return $Call.ByID(3296556194, path);
}

/**
 * StartImport re-scans sourceFolder, then copies qualifying files to the NAS
 * root in a background goroutine. extensions filters by file type (empty = all).
 * When deleteAfterCopy is true, each source file is removed after a successful copy.
 * FITS files are indexed into the database immediately after being copied.
 * Progress is reported via "import:progress" events.
 */
export function StartImport(sourceFolder: string, extensions: string[], deleteAfterCopy: boolean): $CancellablePromise<void> {
    return $Call.ByID(1581009823, sourceFolder, extensions, deleteAfterCopy);
}

/**
 * SuggestRejects returns quality-analyzed light frames whose FWHM is more than
 * threshold standard deviations above the median for their (object, filter) group.
 * threshold defaults to 2.0 if ≤ 0.
 */
export function SuggestRejects(rootPath: string, threshold: number): $CancellablePromise<$models.SuggestResult[]> {
    return $Call.ByID(1563214480, rootPath, threshold).then(($result: any) => {
        return $$createType30($result);
    });
}

/**
 * UnrejectFile removes the soft-delete mark, making the file visible again.
 */
export function UnrejectFile(path: string): $CancellablePromise<void> {
    return $Call.ByID(2416326180, path);
}

/**
 * UpdateFrameMeta writes user-supplied metadata overrides into the DB.
 * Empty fields are ignored — they leave the existing value unchanged.
 */
export function UpdateFrameMeta(path: string, meta: store$0.FrameMeta): $CancellablePromise<void> {
    return $Call.ByID(530878317, path, meta);
}

// Private type creation functions
const $$createType0 = siril$0.SirilInfo.createFrom;
const $$createType1 = $models.Project.createFrom;
const $$createType2 = fits$0.RawPreviewData.createFrom;
const $$createType3 = catalog$0.Annotation.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $models.AppInfo.createFrom;
const $$createType6 = $models.AtlasFrameSize.createFrom;
const $$createType7 = $models.AtlasIndexEntry.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = $models.CatalogObject.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = $models.StorageNode.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = $models.LibraryFrame.createFrom;
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = $models.PagedLightFrames.createFrom;
const $$createType16 = $Create.Array($Create.Any);
const $$createType17 = $models.ProjectOutputFile.createFrom;
const $$createType18 = $Create.Array($$createType17);
const $$createType19 = $models.FileEntry.createFrom;
const $$createType20 = $Create.Array($$createType19);
const $$createType21 = $models.EnrichedFileEntry.createFrom;
const $$createType22 = $Create.Array($$createType21);
const $$createType23 = $Create.Array($$createType1);
const $$createType24 = store$0.Prefs.createFrom;
const $$createType25 = fits$0.FITSHeader.createFrom;
const $$createType26 = $Create.Nullable($$createType25);
const $$createType27 = importer$0.Candidate.createFrom;
const $$createType28 = $Create.Array($$createType27);
const $$createType29 = $models.SuggestResult.createFrom;
const $$createType30 = $Create.Array($$createType29);
