// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as importer$0 from "../importer/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as siril$0 from "../siril/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

/**
 * AppInfo contains read-only runtime information surfaced in the Settings view.
 */
export class AppInfo {
    "dbPath": string;
    "serverPort": number;
    "serverUrl": string;

    /**
     * "EIRIN_PORT env var" or "default"
     */
    "portSource": string;

    /** Creates a new AppInfo instance. */
    constructor($$source: Partial<AppInfo> = {}) {
        if (!("dbPath" in $$source)) {
            this["dbPath"] = "";
        }
        if (!("serverPort" in $$source)) {
            this["serverPort"] = 0;
        }
        if (!("serverUrl" in $$source)) {
            this["serverUrl"] = "";
        }
        if (!("portSource" in $$source)) {
            this["portSource"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): AppInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppInfo($$parsedSource as Partial<AppInfo>);
    }
}

/**
 * AtlasFrameSize holds the pixel dimensions read from a FITS header.
 * Fetched lazily by the frontend when a frame enters the viewport at sufficient zoom.
 */
export class AtlasFrameSize {
    "width": number;
    "height": number;

    /** Creates a new AtlasFrameSize instance. */
    constructor($$source: Partial<AtlasFrameSize> = {}) {
        if (!("width" in $$source)) {
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            this["height"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AtlasFrameSize instance from a string or object.
     */
    static createFrom($$source: any = {}): AtlasFrameSize {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AtlasFrameSize($$parsedSource as Partial<AtlasFrameSize>);
    }
}

/**
 * AtlasIndexEntry holds the DB-resident data for a single stacked/processed
 * frame. Width and Height are NOT included — they require a FITS read and are
 * fetched lazily via GetAtlasFrameSize when the frame is visible in the viewport.
 */
export class AtlasIndexEntry {
    "nasPath": string;
    "name": string;
    "object": string;
    "frameType": string;
    "ra": number;
    "dec": number;

    /**
     * arcsec/pixel
     */
    "pixelScale": number;

    /**
     * degrees (N through E)
     */
    "rotation": number;

    /** Creates a new AtlasIndexEntry instance. */
    constructor($$source: Partial<AtlasIndexEntry> = {}) {
        if (!("nasPath" in $$source)) {
            this["nasPath"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("object" in $$source)) {
            this["object"] = "";
        }
        if (!("frameType" in $$source)) {
            this["frameType"] = "";
        }
        if (!("ra" in $$source)) {
            this["ra"] = 0;
        }
        if (!("dec" in $$source)) {
            this["dec"] = 0;
        }
        if (!("pixelScale" in $$source)) {
            this["pixelScale"] = 0;
        }
        if (!("rotation" in $$source)) {
            this["rotation"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AtlasIndexEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): AtlasIndexEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AtlasIndexEntry($$parsedSource as Partial<AtlasIndexEntry>);
    }
}

/**
 * CatalogObject is a catalog entry exposed to the frontend for the Sky Atlas overlay.
 */
export class CatalogObject {
    "ra": number;
    "dec": number;
    "name": string;
    "type": string;
    "mag": number;

    /** Creates a new CatalogObject instance. */
    constructor($$source: Partial<CatalogObject> = {}) {
        if (!("ra" in $$source)) {
            this["ra"] = 0;
        }
        if (!("dec" in $$source)) {
            this["dec"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("mag" in $$source)) {
            this["mag"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CatalogObject instance from a string or object.
     */
    static createFrom($$source: any = {}): CatalogObject {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CatalogObject($$parsedSource as Partial<CatalogObject>);
    }
}

/**
 * EnrichedFileEntry extends FileEntry with FITS header metadata loaded from
 * the local cache. Fields are zero/empty when HasMeta is false.
 */
export class EnrichedFileEntry {
    "name": string;
    "path": string;
    "isDir": boolean;
    "modTime": time$0.Time;
    "size": number;
    "object": string;
    "filter": string;
    "expTime": number;
    "dateObs": string;
    "gain": number;
    "ccdTemp": number;
    "telescope": string;
    "instrument": string;
    "hasMeta": boolean;
    "isRejected": boolean;
    "rejectionReason": string;

    /** Creates a new EnrichedFileEntry instance. */
    constructor($$source: Partial<EnrichedFileEntry> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("isDir" in $$source)) {
            this["isDir"] = false;
        }
        if (!("modTime" in $$source)) {
            this["modTime"] = null;
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("object" in $$source)) {
            this["object"] = "";
        }
        if (!("filter" in $$source)) {
            this["filter"] = "";
        }
        if (!("expTime" in $$source)) {
            this["expTime"] = 0;
        }
        if (!("dateObs" in $$source)) {
            this["dateObs"] = "";
        }
        if (!("gain" in $$source)) {
            this["gain"] = 0;
        }
        if (!("ccdTemp" in $$source)) {
            this["ccdTemp"] = 0;
        }
        if (!("telescope" in $$source)) {
            this["telescope"] = "";
        }
        if (!("instrument" in $$source)) {
            this["instrument"] = "";
        }
        if (!("hasMeta" in $$source)) {
            this["hasMeta"] = false;
        }
        if (!("isRejected" in $$source)) {
            this["isRejected"] = false;
        }
        if (!("rejectionReason" in $$source)) {
            this["rejectionReason"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EnrichedFileEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): EnrichedFileEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EnrichedFileEntry($$parsedSource as Partial<EnrichedFileEntry>);
    }
}

export class FileEntry {
    "name": string;
    "path": string;
    "isDir": boolean;
    "modTime": time$0.Time;
    "size": number;

    /** Creates a new FileEntry instance. */
    constructor($$source: Partial<FileEntry> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("isDir" in $$source)) {
            this["isDir"] = false;
        }
        if (!("modTime" in $$source)) {
            this["modTime"] = null;
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): FileEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileEntry($$parsedSource as Partial<FileEntry>);
    }
}

/**
 * ImportCandidate is a file in the source folder not yet in the library.
 * Re-exported from the importer package for Wails binding compatibility.
 */
export const ImportCandidate = importer$0.Candidate;

/**
 * ImportCandidate is a file in the source folder not yet in the library.
 * Re-exported from the importer package for Wails binding compatibility.
 */
export type ImportCandidate = importer$0.Candidate;

/**
 * LibraryFrame is the data exported to the frontend for the library view.
 */
export class LibraryFrame {
    "nasPath": string;
    "fileName": string;
    "frameType": string;
    "object": string;
    "filter": string;
    "expTime": number;
    "dateObs": string;
    "gain": number;
    "ccdTemp": number;
    "telescope": string;
    "instrument": string;
    "fileSize": number;
    "isRejected": boolean;

    /**
     * Plate solve results (zero when not solved)
     */
    "ra": number;
    "dec": number;

    /**
     * arcsec/pixel
     */
    "pixelScale": number;

    /**
     * degrees
     */
    "rotation": number;
    "wcsSolved": boolean;

    /**
     * Quality metrics from Siril analysis (zero-value when not yet analyzed)
     */
    "fwhm": number;

    /**
     * "px" or "arcsec"
     */
    "fwhmUnit": string;
    "background": number;
    "noise": number;

    /**
     * Background/Noise ratio
     */
    "snr": number;
    "starCount": number;
    "qualityAnalyzed": boolean;

    /**
     * Moon phase at capture time (0=new moon, 1=full moon; -1 when dateObs unavailable)
     */
    "moonPhase": number;

    /** Creates a new LibraryFrame instance. */
    constructor($$source: Partial<LibraryFrame> = {}) {
        if (!("nasPath" in $$source)) {
            this["nasPath"] = "";
        }
        if (!("fileName" in $$source)) {
            this["fileName"] = "";
        }
        if (!("frameType" in $$source)) {
            this["frameType"] = "";
        }
        if (!("object" in $$source)) {
            this["object"] = "";
        }
        if (!("filter" in $$source)) {
            this["filter"] = "";
        }
        if (!("expTime" in $$source)) {
            this["expTime"] = 0;
        }
        if (!("dateObs" in $$source)) {
            this["dateObs"] = "";
        }
        if (!("gain" in $$source)) {
            this["gain"] = 0;
        }
        if (!("ccdTemp" in $$source)) {
            this["ccdTemp"] = 0;
        }
        if (!("telescope" in $$source)) {
            this["telescope"] = "";
        }
        if (!("instrument" in $$source)) {
            this["instrument"] = "";
        }
        if (!("fileSize" in $$source)) {
            this["fileSize"] = 0;
        }
        if (!("isRejected" in $$source)) {
            this["isRejected"] = false;
        }
        if (!("ra" in $$source)) {
            this["ra"] = 0;
        }
        if (!("dec" in $$source)) {
            this["dec"] = 0;
        }
        if (!("pixelScale" in $$source)) {
            this["pixelScale"] = 0;
        }
        if (!("rotation" in $$source)) {
            this["rotation"] = 0;
        }
        if (!("wcsSolved" in $$source)) {
            this["wcsSolved"] = false;
        }
        if (!("fwhm" in $$source)) {
            this["fwhm"] = 0;
        }
        if (!("fwhmUnit" in $$source)) {
            this["fwhmUnit"] = "";
        }
        if (!("background" in $$source)) {
            this["background"] = 0;
        }
        if (!("noise" in $$source)) {
            this["noise"] = 0;
        }
        if (!("snr" in $$source)) {
            this["snr"] = 0;
        }
        if (!("starCount" in $$source)) {
            this["starCount"] = 0;
        }
        if (!("qualityAnalyzed" in $$source)) {
            this["qualityAnalyzed"] = false;
        }
        if (!("moonPhase" in $$source)) {
            this["moonPhase"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LibraryFrame instance from a string or object.
     */
    static createFrom($$source: any = {}): LibraryFrame {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LibraryFrame($$parsedSource as Partial<LibraryFrame>);
    }
}

/**
 * PagedLightFrames is returned by GetLightFramesPaged.
 */
export class PagedLightFrames {
    "frames": LibraryFrame[];
    "hasMore": boolean;

    /** Creates a new PagedLightFrames instance. */
    constructor($$source: Partial<PagedLightFrames> = {}) {
        if (!("frames" in $$source)) {
            this["frames"] = [];
        }
        if (!("hasMore" in $$source)) {
            this["hasMore"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PagedLightFrames instance from a string or object.
     */
    static createFrom($$source: any = {}): PagedLightFrames {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("frames" in $$parsedSource) {
            $$parsedSource["frames"] = $$createField0_0($$parsedSource["frames"]);
        }
        return new PagedLightFrames($$parsedSource as Partial<PagedLightFrames>);
    }
}

/**
 * Project is the frontend-facing project type.
 */
export class Project {
    "id": number;
    "name": string;
    "description": string;
    "folder": string;
    "createdAt": string;

    /** Creates a new Project instance. */
    constructor($$source: Partial<Project> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("folder" in $$source)) {
            this["folder"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Project instance from a string or object.
     */
    static createFrom($$source: any = {}): Project {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Project($$parsedSource as Partial<Project>);
    }
}

/**
 * ProjectOutputFile describes a file in the project root (outside lights/).
 */
export class ProjectOutputFile {
    "name": string;
    "path": string;
    "size": number;
    "modTime": string;

    /** Creates a new ProjectOutputFile instance. */
    constructor($$source: Partial<ProjectOutputFile> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("modTime" in $$source)) {
            this["modTime"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProjectOutputFile instance from a string or object.
     */
    static createFrom($$source: any = {}): ProjectOutputFile {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProjectOutputFile($$parsedSource as Partial<ProjectOutputFile>);
    }
}

/**
 * SirilInfo describes the detected (or user-configured) Siril installation.
 * Re-exported from the siril package for Wails binding compatibility.
 */
export const SirilInfo = siril$0.SirilInfo;

/**
 * SirilInfo describes the detected (or user-configured) Siril installation.
 * Re-exported from the siril package for Wails binding compatibility.
 */
export type SirilInfo = siril$0.SirilInfo;

/**
 * StorageNode is one node in the storage treemap hierarchy.
 */
export class StorageNode {
    "label": string;
    "totalBytes": number;
    "frameCount": number;
    "children"?: StorageNode[];

    /** Creates a new StorageNode instance. */
    constructor($$source: Partial<StorageNode> = {}) {
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("totalBytes" in $$source)) {
            this["totalBytes"] = 0;
        }
        if (!("frameCount" in $$source)) {
            this["frameCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StorageNode instance from a string or object.
     */
    static createFrom($$source: any = {}): StorageNode {
        const $$createField3_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("children" in $$parsedSource) {
            $$parsedSource["children"] = $$createField3_0($$parsedSource["children"]);
        }
        return new StorageNode($$parsedSource as Partial<StorageNode>);
    }
}

/**
 * SuggestResult is a frame flagged as a statistical outlier within its group.
 */
export class SuggestResult {
    "frame": LibraryFrame;

    /**
     * median FWHM of the (object, filter) group
     */
    "groupMedian": number;

    /**
     * std dev FWHM of the group
     */
    "groupSigma": number;

    /**
     * how many σ above median this frame is
     */
    "sigmas": number;

    /** Creates a new SuggestResult instance. */
    constructor($$source: Partial<SuggestResult> = {}) {
        if (!("frame" in $$source)) {
            this["frame"] = (new LibraryFrame());
        }
        if (!("groupMedian" in $$source)) {
            this["groupMedian"] = 0;
        }
        if (!("groupSigma" in $$source)) {
            this["groupSigma"] = 0;
        }
        if (!("sigmas" in $$source)) {
            this["sigmas"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SuggestResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SuggestResult {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("frame" in $$parsedSource) {
            $$parsedSource["frame"] = $$createField0_0($$parsedSource["frame"]);
        }
        return new SuggestResult($$parsedSource as Partial<SuggestResult>);
    }
}

// Private type creation functions
const $$createType0 = LibraryFrame.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = StorageNode.createFrom;
const $$createType3 = $Create.Array($$createType2);
